baseURL = "https://www.legendesdelatable.fr/"
languageCode = "fr-fr"
title = "Les Légendes de la Table"
theme = "ananke"
disqusShortname = "legendesdelatable"
author = "Philippe Lemaire"
description = "Carnets Rôlistes d’un MJ lyonnais"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"

Paginate = 10

enableRobotsTXT = true
#
SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  favicon = "/images/favicon.png"
  site_logo = ""
  description = "Carnets Rôlistes d’un MJ lyonnais"
  Subtitle = "Carnets Rôlistes d’un MJ lyonnais"
  SiteDescription = "Carnets Rôlistes d’un MJ lyonnais"
  rss = "/index.xml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/static/images/book-shelf.jpg"
  cover = "/images/book-shelf.jpg"
  recent_posts_number = 5
  AuthorName = "Philippe Lemaire"
